### ISSUE TITLE
Do you have a copy of Flixster dataset

### ISSUE THREAD

**Issue by wenmin-wu** [tkamishima/kamrecsys#1]
Hi,
   The link you provided to download Flixster dataset is not available any more, do you have a copy of it? Thx!

**Comment by tkamishima** [comment]
I have it, but unfortunately no license term is not specified, and it is unclear whether or not re-distribution is allowed.  https://www.linkedin.com/in/mohsenjamali/ would be Dr. Jamali's LinkedIn profile.  I consider it better to contact him.

**Comment by wenmin-wu** [comment]
@tkamishima hi, I sent InMail to Dr. Jamali through LinkedIn 11 days ago but haven't got any reply. Do you have his personal email ? I just want to replay the results of previous works using this dataset, and won't use this dataset in public. I will be mostly grateful if you could share this dataset with me! my email is wu_wenmin@126.com.

**Comment by tkamishima** [comment]
Unfortunately, I don't know his contact information.

And, I cannot redistribute Dr. Jamali's copyright material without his permission.
